on:
  push: {}
  pull_request: {}
jobs:
  nix_run:
    strategy:
      fail-fast: false
      matrix:
        app:
        - compose.ab
        target_host:
        - baseline.
        - proxy.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: cachix/install-nix-action@v31
    - run: nix run -L '.?submodules=1#${{ matrix.app }}' -- ${{ matrix.target_host }}
    - uses: actions/upload-artifact@v4
      with:
        path: benchmark/
