on:
  pull_request: *push
  push: &push
    paths:
    - "thesis/**"
jobs:
  nix_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: cachix/install-nix-action@v31
    - run: >-
        GIT_BUNDLE="tmp/tex/crash-tolerant-proxy-$(git rev-parse --verify --short ${{ github.ref }}).bundle"
        && cd thesis
        && mkdir -p "$(dirname "$GIT_BUNDLE")"
        && git fetch --unshallow
        && git bundle create "$GIT_BUNDLE" ${{ github.ref }}
        && git add --force --intent-to-add "$GIT_BUNDLE"
        && sed -e "/^PDF_ATTACHMENTS = \\\\$/ a $GIT_BUNDLE \\\\" -i GNUmakefile
    - run: nix build -L ./thesis#default
    - uses: actions/upload-artifact@v4
      with:
        path: result/
